# Generated by Django 3.2.4 on 2021-06-09 14:37

import ckeditor.fields
from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', ckeditor.fields.RichTextField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=False)),
                ('preview', models.ImageField(upload_to=product.models.upload_image_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
